"""add password authentication fields

Revision ID: 201453e920f3
Revises: c669149de5a3
Create Date: 2026-01-13 14:36:38.860749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201453e920f3'
down_revision: Union[str, None] = 'c669149de5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reminders_date_time_utc_status', table_name='reminders')
    op.create_index(op.f('ix_reminders_date_time_utc'), 'reminders', ['date_time_utc'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Bcrypt hashed password'))
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True, comment='Secure token for password reset'))
    op.add_column('users', sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True, comment='Expiration datetime for reset token'))
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_column('users', 'reset_token_expires_at')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_reminders_date_time_utc'), table_name='reminders')
    op.create_index('ix_reminders_date_time_utc_status', 'reminders', ['date_time_utc', 'status'], unique=False)
    # ### end Alembic commands ###
